### ISSUE TITLE
Label filtering layer list incomplete

### ISSUE THREAD

**Issue by Libarch** [aeag/mask_plugin#22]
(Using v1.2 on QGIS 2.8.1 Windows 64)
Not all vector layers are listed in the table, so it is not possible to filter unlisted layers - see attached views for example (layer "Leaflet rounds" is not listed, although it is a vector layer). Please let me know if/what more info needed
![layers table](https://cloud.githubusercontent.com/assets/11440306/6617448/adbcb54e-c8b0-11e4-9317-1c7bb6b0edb7.PNG)
![plugin table](https://cloud.githubusercontent.com/assets/11440306/6617449/adc9155a-c8b0-11e4-925a-e2ca54da7b71.PNG)

**Comment by haubourg** [comment]
Hi, 
layers listed are only vector layers that have labeling activated. Is that the case for your Leaflet rounds layer? 
Cheers

**Comment by Libarch** [comment]
Now I understand! I had de-activated labels temporarily

Merci beaucoup

Rick
